apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  namespace: ${BRANCH}
spec:
  selector:
    matchLabels:
      app: nginx-phpfpm
  template:
    metadata:
      labels:
        app: nginx-phpfpm
    spec:
      containers:
      - name: nginx-phpfpm
        image: 728490037630.dkr.ecr.eu-north-1.amazonaws.com/bigproject_${SERVICE}_${BRANCH}:${TAG}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 150Mi 
      imagePullSecrets:
      - name: regcred         
